<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.example.org/2ndHandBike/PaymentService/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="PaymentService" targetNamespace="http://www.example.org/2ndHandBike/PaymentService/">
  <wsdl:message name="PaymentRequest">
    <wsdl:part name="id" type="xsd:string"/>
    <wsdl:part name="amount" type="xsd:double"></wsdl:part>
    <wsdl:part name="token" type="xsd:string"></wsdl:part>
    <wsdl:part name="orderId" type="xsd:int"></wsdl:part>
  </wsdl:message>
  <wsdl:message name="PaymentResponse">
  </wsdl:message>
  <wsdl:portType name="PaymentService">
    <wsdl:operation name="Payment">
      <wsdl:input message="tns:PaymentRequest"/>
      <wsdl:output message="tns:PaymentResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="PaymentServiceSOAP" type="tns:PaymentService">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Payment">
      <soap:operation soapAction="http://www.example.org/2ndHandBike/PaymentService/Payment"/>
      <wsdl:input>
        <soap:body namespace="http://www.example.org/2ndHandBike/PaymentService/" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body namespace="http://www.example.org/2ndHandBike/PaymentService/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="PaymentService">
    <wsdl:port binding="tns:PaymentServiceSOAP" name="PaymentServiceSOAP">
      <soap:address location="http://www.example.org/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
